// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication16;

namespace WebApplication16.Migrations
{
    [DbContext(typeof(sistemDbcontext))]
    partial class sistemDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication16.Models.Apple", b =>
                {
                    b.Property<int>("AppleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppleAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppleId");

                    b.ToTable("Apples");
                });

            modelBuilder.Entity("WebApplication16.Models.Mudur", b =>
                {
                    b.Property<int>("MudurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MudurAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MudurAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MudurEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MudurSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelTc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonelTcNavigationPersonelId")
                        .HasColumnType("int");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MudurId");

                    b.HasIndex("PersonelTcNavigationPersonelId");

                    b.HasIndex("UrunId");

                    b.ToTable("Mudurs");
                });

            modelBuilder.Entity("WebApplication16.Models.Oppo", b =>
                {
                    b.Property<int>("OppoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OppoAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OppoId");

                    b.ToTable("Oppos");
                });

            modelBuilder.Entity("WebApplication16.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonelAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelId");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("WebApplication16.Models.Samsung", b =>
                {
                    b.Property<int>("SamsungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SamsungAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SamsungFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SamsungId");

                    b.ToTable("Samsungs");
                });

            modelBuilder.Entity("WebApplication16.Models.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppleId")
                        .HasColumnType("int");

                    b.Property<int?>("OppoId")
                        .HasColumnType("int");

                    b.Property<int?>("SamsungId")
                        .HasColumnType("int");

                    b.Property<int?>("XiaomiId")
                        .HasColumnType("int");

                    b.HasKey("UrunId");

                    b.HasIndex("AppleId");

                    b.HasIndex("OppoId");

                    b.HasIndex("SamsungId");

                    b.HasIndex("XiaomiId");

                    b.ToTable("Urunlers");
                });

            modelBuilder.Entity("WebApplication16.Models.Xiaomi", b =>
                {
                    b.Property<int>("XiaomiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XiaomiAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XiaomiId");

                    b.ToTable("Xiaomis");
                });

            modelBuilder.Entity("WebApplication16.Models.Mudur", b =>
                {
                    b.HasOne("WebApplication16.Models.Personel", "PersonelTcNavigation")
                        .WithMany("Mudurs")
                        .HasForeignKey("PersonelTcNavigationPersonelId");

                    b.HasOne("WebApplication16.Models.Urunler", "Urun")
                        .WithMany("Mudurs")
                        .HasForeignKey("UrunId");

                    b.Navigation("PersonelTcNavigation");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("WebApplication16.Models.Urunler", b =>
                {
                    b.HasOne("WebApplication16.Models.Apple", "Apple")
                        .WithMany("Urunlers")
                        .HasForeignKey("AppleId");

                    b.HasOne("WebApplication16.Models.Oppo", "Oppo")
                        .WithMany("Urunlers")
                        .HasForeignKey("OppoId");

                    b.HasOne("WebApplication16.Models.Samsung", "Samsung")
                        .WithMany("Urunlers")
                        .HasForeignKey("SamsungId");

                    b.HasOne("WebApplication16.Models.Xiaomi", "Xiaomi")
                        .WithMany("Urunlers")
                        .HasForeignKey("XiaomiId");

                    b.Navigation("Apple");

                    b.Navigation("Oppo");

                    b.Navigation("Samsung");

                    b.Navigation("Xiaomi");
                });

            modelBuilder.Entity("WebApplication16.Models.Apple", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("WebApplication16.Models.Oppo", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("WebApplication16.Models.Personel", b =>
                {
                    b.Navigation("Mudurs");
                });

            modelBuilder.Entity("WebApplication16.Models.Samsung", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("WebApplication16.Models.Urunler", b =>
                {
                    b.Navigation("Mudurs");
                });

            modelBuilder.Entity("WebApplication16.Models.Xiaomi", b =>
                {
                    b.Navigation("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
